import json
import logging
from typing import Any, Dict, Optional
from utils.llm import LLMClient
from utils.parser import Parser
from utils.config import Config


logger = logging.getLogger(__name__)


class ReviewAgent:
    """Safety reviewer agent - validates responses before delivery."""

    def __init__(self, llm_client: LLMClient, config: Config):
        self.llm = llm_client
        self.config = config
        self.parser = Parser()
        self.sop_data: Dict[str, Any] = {}
        self.kb_data: Dict[str, Any] = {}
        self._load_sop()
        self._load_knowledge_base()

    def _load_sop(self) -> None:
        """Load SOP data from JSON file."""
        try:
            sop_path = self.config.get_sop_path()
            with open(sop_path, "r") as f:
                self.sop_data = json.load(f)
            logger.info("SOP data loaded for review agent")
        except FileNotFoundError:
            logger.error(f"SOP file not found at {self.config.get_sop_path()}")
            raise
        except json.JSONDecodeError:
            logger.error("Failed to parse SOP JSON")
            raise

    def _load_knowledge_base(self) -> None:
        """Load knowledge base data."""
        try:
            kb_path = self.config.get_knowledge_base_path()
            with open(kb_path, "r") as f:
                self.kb_data = json.load(f)
            logger.info("Knowledge base loaded for review agent")
        except FileNotFoundError:
            logger.warning("Knowledge base not found for review agent")
            self.kb_data = {}

    def _load_prompt_template(self) -> str:
        """Load review prompt template."""
        try:
            prompt_path = self.config.get_prompt_path("review_prompt")
            with open(prompt_path, "r") as f:
                return f.read()
        except FileNotFoundError:
            logger.error(f"Review prompt not found at {prompt_path}")
            raise

    def validate(self, customer_message: str, generated_response: str,
                 confidence: float, source: str = "llm_sop") -> Dict[str, Any]:
        """
        Validate AI-generated response before sending to customer.

        Args:
            customer_message: Original customer message
            generated_response: Response generated by FAQ agent
            confidence: Confidence score from FAQ agent

        Returns:
            Validation result with approval status and risk level
        """
        try:
            # Auto-fail if confidence is too low
            if confidence < self.config.confidence_threshold:
                logger.warning(f"Review: rejecting response due to low confidence ({confidence:.2f})")
                return {
                    "approved": False,
                    "risk": "high",
                    "reason": f"Confidence score {confidence:.2f} below threshold {self.config.confidence_threshold}"
                }

            # Load prompt
            prompt_template = self._load_prompt_template()
            sop_text = self._format_sop(self.sop_data)

            kb_text = self._format_kb(self.kb_data)
            system_prompt = prompt_template.format(
                sop_data=sop_text,
                kb_data=kb_text,
                customer_message=customer_message,
                generated_response=generated_response,
                confidence=confidence,
                source=source
            )

            # Call LLM for deeper validation
            response_text = self.llm.call(
                system_prompt=system_prompt,
                user_message="Validate this response",
                temperature=0.1
            )

            if not response_text:
                logger.error("LLM call failed in review agent")
                return {
                    "approved": False,
                    "risk": "high",
                    "reason": "Review agent failed to validate response"
                }

            # Parse review result
            parsed = self.parser.parse_json(response_text)
            if not parsed:
                logger.warning(f"Failed to parse review response: {response_text[:100]}")
                return {
                    "approved": False,
                    "risk": "high",
                    "reason": "Review response parsing failed"
                }

            # Validate review response structure
            if not self.parser.validate_review_response(parsed):
                logger.warning(f"Invalid review response structure: {parsed}")
                return {
                    "approved": False,
                    "risk": "high",
                    "reason": "Review response missing required fields"
                }

            logger.info(f"Review result: approved={parsed.get('approved')}, risk={parsed.get('risk')}")
            return parsed

        except Exception as e:
            logger.error(f"Error in review agent: {str(e)}")
            return {
                "approved": False,
                "risk": "high",
                "reason": f"Review agent exception: {str(e)}"
            }

    @staticmethod
    def _format_sop(sop_data: Dict[str, Any]) -> str:
        """Format SOP data as readable text."""
        lines = [
            f"Business: {sop_data.get('business', 'N/A')}",
            f"Hours: {sop_data.get('hours', 'N/A')}",
            f"Phone: {sop_data.get('phone', 'N/A')}",
            f"Location: {sop_data.get('location', 'N/A')}",
            "\nServices:"
        ]
        for service, price in sop_data.get('services', {}).items():
            lines.append(f"  - {service}: {price}")
        lines.append(f"\nBooking: {sop_data.get('booking', 'N/A')}")
        lines.append(f"Cancellation: {sop_data.get('cancellation', 'N/A')}")
        return "\n".join(lines)

    @staticmethod
    def _format_kb(kb_data: Dict[str, Any]) -> str:
        """Format knowledge base as readable text."""
        if not kb_data:
            return "No knowledge base available."
        lines = []
        for key, value in kb_data.items():
            if key == "clinic_information":
                continue
            if isinstance(value, dict):
                desc = value.get("description") or value.get("booking") or ""
                if desc:
                    lines.append(f"{key}: {desc}")
        return "\n".join(lines) if lines else "No additional knowledge available."
